name: "godot-ci export"
on:
  pull_request:
    branches: [main]

permissions:
  contents: write

# NOTE: If your `project.godot` is at the repository root, set `PROJECT_PATH` below to ".".

env:
  GODOT_VERSION: 4.7
  EXPORT_NAME: spg-template
  PROJECT_PATH: .

jobs:
  godot_build:
    runs-on: ubuntu-24.04
    steps:
      - name: Deploy Godot
        uses: Daniel-Griffiths/godot-deploy@master
        with:
          godot-version: "4.7"
          platforms: "web,windows,linux"
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        if: github.ref == 'refs/heads/master'
        with:
          tag_name: latest
          name: Latest Build
          files: |
            build/windows/windows.zip
            build/linux/linux.tar
            build/web/web.tar
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
